### ISSUE TITLE
Encoding of NIL

### ISSUE THREAD

**Issue by mmontone** [equill/neo4cl#23]
In the code it is mentioned that empty list is encoded as null, but that is not the case:

```
NEOSW> (neo4cl::encode-element '())
#(160)
NEOSW> (neo4cl::encode-element :null)
#(192)
NEOSW> (neo4cl::encode-null)
#(192)
```

I don't know if this is OK or not. Just letting you know, as I stumbled when passing NIL as a parameter of a query, gets encoded as an empty list, not null, and signals an error (neo4j only allows primitive types in query parameters, and a list is not a primitive type). 

I have to explicitly use `:null` in query parameters. Or add this:

```
(defmethod neo4cl::encode-element ((element (eql nil)))
	 (neo4cl::encode-null))
```

**Comment by mmontone** [comment]
To be clearer, this query fails with: "Bolt error [Neo.ClientError.Statement.TypeError]: Property values can only be of primitive types or arrays thereof. Encountered: Map{}."

```
(neo4cl:bolt-transaction-autocommit *db* "CREATE (o:MyObject {x: $x})" :parameters '(("x" . nil)))
```

this works:

```
(neo4cl:bolt-transaction-autocommit *db* "CREATE (o:MyObject {x: $x})" :parameters '(("x" . :null)))
```

I guess that's OK as there's no good way of solving the ambiguity of NIL in Common Lisp. But letting you know just in case.

**Comment by equill** [comment]
You're right: I failed to handle that case, despite documenting it.

You guessed correctly, too: I had to resolve the ambiguity somehow, and this was the least-bad option I could think of. If you can suggest a better way to handle this, I'd love to know about it, because I don't really like this solution either.

**Comment by mmontone** [comment]
The NIL ambiguity problem is one of the things I don't like about CL. I know, if I say it out loud, everyone will tell me I'm wrong. But it causes problems in lots of places. JSON encoding libraries, Postmodern, and it will be a problem in this library too. I haven't seen a good solution anywhere.

**Comment by equill** [comment]
You're in good company regarding that ambiguity; I'd prefer an explicit boolean type, too.

I've started work on fixing this, because I can at least see what needs fixing. It'll take time to extend the testing and be happy with that but, if you're willing to live on the bleeding edge, there's now a `23_Encode_empty_lists_as_Null` branch in this repo so you can follow along there.

**Comment by mmontone** [comment]
> You're in good company regarding that ambiguity; I'd prefer an explicit boolean type, too.

And you would also need an explicit `list` too somehow, as NIL can be either null or empty list.
I suspect Clojure implements a solution for this, but Clojure doesn't have CONS lists, so ...

Sometimes a "solution" is to force more explicit datatypes, like instead of lists, use vectors. And let's say you want to encode some "object" as an alist, use a hash-table instead. Etc. But still ...

**Comment by mmontone** [comment]
Btw, I think the current encoding/decoding is "fine". I mean, if user needs to use `:null` instead of NIL, so be it. That's how things are handled in other libraries like Postmodern, or CL-JSON.

**Comment by equill** [comment]
Now that I'm back at a computer, testing this was simpler than I'd expected.
